"""fragnances table and relation to brandss

Revision ID: e658a2c93047
Revises: c852bb927776
Create Date: 2022-09-01 19:55:45.735538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e658a2c93047'
down_revision = 'c852bb927776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragnance', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_fragnance_price'), 'fragnance', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragnance_price'), table_name='fragnance')
    op.drop_column('fragnance', 'price')
    # ### end Alembic commands ###
